name: Build
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Test coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      -  name: Build artifact
         run: mvn clean package
#      - name: Create artifact
#        run: zip -r artifact.zip target/to-do-list-coursework-0.0.1.jar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: to-do-list-coursework-0.0.1.jar
          path: target/to-do-list-coursework-0.0.1.jar

  telegram_sender:
    name: Telegram sender
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: to-do-list-coursework-0.0.1.jar
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: to-do-list-coursework-0.0.1.jar
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}