name: Build
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Maven Verify
        run: mvn -B clean verify

      - name: Test coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      -  name: Build artifact
         run: mvn clean package

      - name: Create artifact zip
        run: zip -r artifact.zip target/to-do-list-coursework-0.0.1.jar

      - name: Upload artifact zip
        uses: actions/upload-artifact@v2
        with:
          name: to-do-list-coursework-0.0.1.jar
          path: artifact.zip

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip target/to-do-list-coursework-0.0.1.jar

      - name: Upload to google drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "archive.zip"
          folderId: ${{ secrets.FOLDER_ID }}
          name: "to-do-list-coursework-0.0.1.zip"

#      - name: Build Docker image
#        run: docker build -t myapp-image .
#      - name: Push Docker image to registry
#        run: docker push my-registry/myapp-image

#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy to server
#        run: |
#          docker stop myapp-container || true
#          docker rm myapp-container || true
#          docker run -d --name myapp-container -p 80:80 my-registry/myapp-image

  telegram_sender:
    name: telegram sender
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: to-do-list-coursework-0.0.1.jar
          path: target
      - name: Print files
      run: cd target && ls -l

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: target/*.jar
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}