name: Build
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Test coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      -  name: Build artifact
         run: mvn clean package
      - name: Create artifact zip
        run: zip -r artifact.zip target/to-do-list-coursework-0.0.1.jar
      - name: Upload artifact zip
        uses: actions/upload-artifact@v2
        with:
          name: to-do-list-coursework-0.0.1.jar
          path: artifact.zip