name: Deploy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkin
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clearing old images
        run: |
          cd docker
          docker-compose down

      - name: ls
        run: ls -la

      - name: Build
        run: ./mvnw clean package -DskipTests

      - name: Build docker image
        run: docker build -t todo-api:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

#      - name: Starting application
#        run: |
#          cd docker
#          docker-compose up -d
#
#            - name: Setup QEMU
#        uses: docker/setup-qemu-action@v2
#
#      - name: Setup Docker Buildx
#        run: |
#          docker build -t todo-api:latest .

      #      - name: Clearing images
      #        run: |
      #          cd docker
      #          docker-compose down

      - name: Build and push
        run: |
          docker tag todo-api:latest pestrikv/todo-api
          docker push ${{secrets.DOCKER_USERNAME}}/todo-api:latest

      - name: Run the application
        run: |
          cd docker
          docker-compose up -d
