name: Deploy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clearing old images
        run: |
          cd docker
          docker-compose down

      - name: ls
        run: ls -la

