name: Deploy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clearing old images
        run: |
          cd docker
          docker-compose down

      - name: ls
        run: ls -la

      - name: Build
        run: ./mvnw clean package -DskipTests

      - name: Build docker image
        run: docker build -t todo-api:latest .

      - name: Starting application
        run: |
          cd docker
          docker-compose up -d

