name: DockerBuilder

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v2
      # Step that sets up QEMU for cross-platform builds

    - name: Set Up Docker BuildX
      uses: docker/setup-buildx-action@v2
      # Step that sets up Docker BuildX for building multi-platform images

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        # Step that logs in to Docker Hub using provided credentials

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        push: true
        tags: pestrikv/todo-api:latest
        # Step that builds the Docker image using the Dockerfile and pushes it to Docker Hub