name: SonarCloud
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify -P sonar -Dsonar.projectKey=pestrikv_tinkoff-to-do-list-coursework -Dsonar.organization=pestrikvtodoactions -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN